version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/fe"
    open-pull-requests-limit: 8
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      patches:
        applies-to: "version-updates"
        update-types:
          - patch
      security-patches:
        applies-to: "security-updates"
        update-types:
          - patch
