ServerName ${SERVER_NAME}

RewriteEngine On
UseCanonicalName On

DocumentRoot ${APACHE_DOCUMENT_ROOT}

<Directory ${APACHE_DOCUMENT_ROOT}>
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
</Directory>

# gzip compression
AddOutputFilterByType DEFLATE text/html text/plain text/css application/javascript application/x-javascript text/xml application/xml application/rss+xml text/javascript image/x-icon image/bmp image/svg+xml

ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://localhost:9000${APACHE_DOCUMENT_ROOT}/$1

# prefix with the container name
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D" combined

ErrorLog /dev/stderr
CustomLog /dev/stdout combined

ProxyTimeout 300
Timeout 300
LimitRequestFieldSize 32768