# For local tests
services:
  backend:
    build: ./php-apache
    working_dir: /var/www/html
    ports:
      - 80:80
    networks:
      - leasingmarkt
    volumes:
      - ../be:/var/www/html
    environment:
      SERVER_NAME: localhost

  cli:
    build: ./php-apache
    restart: "no"
    working_dir: /var/www/html
    entrypoint: "/bin/sh"
    networks:
      - leasingmarkt
    profiles: [cli]
    volumes:
      - ../be:/var/www/html
    environment:
      HOST_UID: 1000
      HOST_GID: 1000
    user: www-data

networks:
  leasingmarkt:
    external: true
